### ISSUE TITLE
Determinations Request Interface for Power Users

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRARequests#28]
The CBRA team has a couple users who make multiple requests and would like to support these users. 
We would like the following enhancement:

> Add a “Submit and Create New” option to the end of the request process, opening a new request and filling in the requestor information with the same as the previous.

**Comment by HansVraga** [comment]
Others, perhaps even more lightweight options:

"Submit and Create New" Option when submitting a Determination Request. Would start a new request with all the requester information populated.

Use of local storage to remember address entered and auto-fill for any further determinations.

**Comment by aaronstephenson** [comment]
Implemented.
