### ISSUE TITLE
Email requester confirmation of receipt of request

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRARequests#40]
Send an email with the same information given on the Case Summary screen (after submission of a new request)

![image](https://cloud.githubusercontent.com/assets/12058013/18442093/76ce9eec-78dd-11e6-9967-56a65c2608b2.png)

**Comment by aaronstephenson** [comment]
The cooperator gave us more specific details on what the confirmation email should be, which I have implemented.

> Coastal Barrier Resources Act Determination Request Received", and perhaps include the reference number or case number?
